services:
  postgres:
    image: postgres:16-alpine
    container_name: fastboat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastboat
    ports:
      - "5432:5432"
    volumes:
      - fastboat_postgres_data:/var/lib/postgresql/data
      - ./infra/database/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql

  redis:
    image: redis:7-alpine
    container_name: fastboat-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: fastboat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  fastboat_postgres_data:
